<?php
namespace Magenest\Rules\Model\ResourceModel;

class Rules extends \Magento\Framework\Model\ResourceModel\Db\AbstractDb
{
    protected $_timelineFactory;
    protected $_date;

    public function __construct(
        \Magenest\Rules\Model\TimelineFactory $timelineFactory,
        \Magento\Framework\Stdlib\DateTime\DateTime $date,
        \Magento\Framework\Model\ResourceModel\Db\Context $context,
        $connectionName = null
    )
    {
        $this->_date = $date;
        $this->_timelineFactory = $timelineFactory;
        parent::__construct($context, $connectionName);
    }

    public function _construct()
    {
        $this->_init('magenest_rules',
            'id');
    }

    protected function _afterSave(\Magento\Framework\Model\AbstractModel $object)
    {
        $date = $this->_date->gmtDate();
        $timeline = $this->_timelineFactory->create();
        $timeline->setStatus('Save');
        $timeline->setTimeline($date);
        $timeline->save();
        return parent::_afterSave($object); // TODO: Change the autogenerated stub
    }

    protected function _afterLoad(\Magento\Framework\Model\AbstractModel $object)
    {
        $date = $this->_date->gmtDate();
        $timeline = $this->_timelineFactory->create();
        $timeline->setStatus('Load');
        $timeline->setTimeline($date);
        $timeline->save();
        return parent::_afterLoad($object); // TODO: Change the autogenerated stub
    }
}